### ISSUE TITLE
[関数] 再帰呼び出しの説明は必要か？

### ISSUE THREAD

**Issue by aTakayukiMorita** [access-company/kotlin_intro#14]
https://github.com/pankona/kotlin_intro/blob/master/src/function.md#%E5%86%8D%E5%B8%B0%E5%91%BC%E3%81%B3%E5%87%BA%E3%81%97
再帰呼び出しの最適化とか入門とするには難しいような気がします。
あと、ローカル関数が再帰呼び出しに含まれているような構成に見えます。

**Comment by pankona** [comment]
末尾呼び出し最適化は使えるケースも少ない気がしていて、あえて入門用資料に書くかは迷いました。
確かに難しいと思います。消すか移動したほうが良い気がしてきました。
書くとしたら TIPS ですかねぇ。
