### ISSUE TITLE
[基本的な文法] 数値のアンダースコアの指定

### ISSUE THREAD

**Issue by aTakayukiMorita** [access-company/kotlin_intro#4]
https://github.com/pankona/kotlin_intro/blob/master/src/basic_syntax.md#%E3%81%84%E3%82%8D%E3%82%93%E3%81%AA%E5%9E%8B

https://kotlinlang.org/docs/reference/basic-types.html#underscores-in-numeric-literals-since-11
数値のアンダースコア指定の説明があってもいいかもしれないです。

**Comment by pankona** [comment]
Kotlin 1.1 からの機能なんですね。参考書に出てこなかったので飛ばしていました。
見やすくなりそうなので、説明追加しておきます！
