### ISSUE TITLE
[継承・抽象クラス] パッケージの説明

### ISSUE THREAD

**Issue by aTakayukiMorita** [access-company/kotlin_intro#5]
https://github.com/pankona/kotlin_intro/blob/master/src/inherit_abstract.md#%E5%8F%AF%E8%A6%96%E6%80%A7
パッケージの説明が、可視性の説明で最初に出てきますが大丈夫ですかね？

**Comment by pankona** [comment]
パッケージの説明、入ってないですね。
いきなり出てくるとびっくりしそうなので、入れてみます！
