### ISSUE TITLE
Type to searchが動かない

### ISSUE THREAD

**Issue by ghost** [access-company/kotlin_intro#62]
ページ左上のType to searchが動いていない様子。
詳しくは見てないが、実は以下が必要だったとか？
https://github.com/access-company/kotlin_intro/pull/57/commits/2c5584fe1232ff70358eff3c1d4af8869000f216#diff-d0656efeb06fe536fce622d8979b74c57c7cb3b999bf85a31599264d195bc9f4L9-L11

**Comment by aKensakuNagauchi** [comment]
head-appendを無効化すれば動くようになる。
https://github.com/access-company/kotlin_intro/blob/master/src/book.json#L5
しかし、head-append無効化はKotlin Playgroundが動かなくなるので、詳しい調査が必要。

**Comment by tonionagauzzi** [comment]
head-appendの説明
https://github.com/NoriSte/gitbook-plugin-head-append
> If you want to add a script you must replace every script occurrence with SCRIPTTAG, the plugin will restore it.

に従い、book.json の `script` を `SCRIPTTAG` に変えたら、Kotlin Playground が有効なまま Type to search も動くようになった
