### ISSUE TITLE
n面のサイコロの問題内容がわかりづらい

### ISSUE THREAD

**Issue by tonionagauzzi** [access-company/kotlin_intro#66]
2022年度新卒研修での指摘で、n面のサイコロの問題内容がわかりづらい

* 「1 以上 n 以下」と書かれているが、nという変数が別の目的で使われている（どうやら1以上diceFace以下ということのようだ）
* 「ちなみに 100 回振ると壊れて例外 Exception("I was broken") を吐く」ってのは、それも課題の1つなのか

改訂案：https://accessjp.slack.com/archives/C035ECGPY7K/p1649211384542459

**Comment by magicant** [comment]
言われてみれば、確かに!
改訂案は LGTM です
